version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./flag.txt:/flag.txt  # Mount the flag file
      - ./templates:/app/templates  # Mount the templates directory
